# Generated by Django 4.1.3 on 2022-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fingerprint1', models.FileField(upload_to='file1', verbose_name='fileone')),
                ('fingerprint2', models.FileField(upload_to='file2', verbose_name='fileone')),
            ],
        ),
    ]
