# Generated by Django 4.1.3 on 2022-11-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fingerprint1',
            field=models.FileField(upload_to='file1', verbose_name='fingerprint1'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='fingerprint2',
            field=models.FileField(upload_to='file2', verbose_name='fingerprint2'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
