# Generated by Django 4.1.3 on 2022-11-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_remove_fileupload_username_alter_fileupload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
