# Generated by Django 4.1.3 on 2022-11-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_fileupload_username_alter_fileupload_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='username',
        ),
    ]
