# Generated by Django 4.1.3 on 2022-11-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_remove_fileupload_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
