# Generated by Django 4.1.3 on 2022-11-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0009_remove_fileupload_username_fileupload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='date',
            new_name='date_uploaded',
        ),
    ]
