# Generated by Django 4.1.3 on 2022-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0010_rename_date_fileupload_date_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(auto_now=True)),
                ('video1', models.FileField(upload_to='video1', verbose_name='video1')),
                ('video2', models.FileField(upload_to='video2', verbose_name='video2')),
            ],
        ),
    ]
